HW №3
Anastasiia-Kochetkova/card-game-skypro pull request #3
Opened 2022-05-24 10:10 UTC by Anastasiia-Kochetkova

###Что было сделано:

 -Сверстала и застилизовала экран игры;
- Реализовала механизм генерации пар карт на странице в зависимости от выбранного уровня сложности;
- Добавила переворот карт рубашкой вверх спустя 5 секунд после отрисовки страницы игры;
- Настроила  **prettier** , **eslint**, **stylelint (.scss)**;
- Подключила **husky** для автопроверки кода перед commit;

2022-05-25 08:43 UTC, mrerberg requested changes

2022-05-25 08:43 UTC, mrerberg commented on index.html
>  <html lang="en">
Сайт на русском же?

2022-05-25 08:43 UTC, mrerberg commented on screens/game.js
> +    const point = document.createElement("div");
Предлагаю написать некую абстрактную функцию, которая будет принимать некие аргументы и заниматься созданием и вставкой в страницу элементов. Так как очень много блоков кода повторяются

2022-05-25 08:43 UTC, mrerberg commented on screens/game.js
> +window.application.screens["game"] = function () {
Данная функция очень большая, ее надо разбить на несколько

2022-05-26 06:43 UTC, Anastasiia-Kochetkova commented on index.html
>  <html lang="en">
Да, на русском. Даже не обращала внимание на эту строку раньше. Спасибо)

2022-05-26 07:18 UTC, Anastasiia-Kochetkova commented on screens/game.js
> +window.application.screens["game"] = function () {
Хорошо, попробую разбить, но пока не совсем понимаю, как это реализовать. Ведь эта функция отрисовки экрана и мы ее вызываем при клике на кнопку старт.  window.application.screens["game"] можно сразу несколько функций присвоить? Или потом отдельные блоки-функции собрать в одну функцию (вызвать их там) и уже её присвоить?

2022-05-26 07:40 UTC, Anastasiia-Kochetkova commented on screens/game.js
> +    const point = document.createElement("div");
Вы имеете в виду использование шаблонизатора? Согласна, что блоки с минутами и секундами лучше сделать через функцию, но я написала их на ванильном в целях экономии времени, т.к. этот способ мне кажется наиболее понятным. В будущем вернусь к этому месту и попробую оптимизировать.

2022-05-26 18:59 UTC, Anastasiia-Kochetkova commented on screens/game.js
> +window.application.screens["game"] = function () {
Поправила. Прошу проверить.

2022-05-26 20:24 UTC, Anastasiia-Kochetkova commented on screens/game.js
> +    const point = document.createElement("div");
Переделала вот так. Вроде стало удобнее. https://github.com/Anastasiia-Kochetkova/card-game-skypro/pull/3/commits/58cbd8611dff770c2b60e1cca969637858f7460e

2022-06-07 16:19 UTC, merged