Hw 4
Anastasiia-Kochetkova/card-game-skypro pull request #4
Opened 2022-06-01 21:01 UTC by Anastasiia-Kochetkova

### Что было сделано: ###
- Установлен и настроен *** Webpack *** ;
- Добавлено сравнение двух выбранных карточек на экране игры;

2022-06-03 07:55 UTC, mrerberg requested changes

2022-06-03 07:55 UTC, mrerberg commented on src/card-collection.js
> +        image: "./static/cards/11.jpg",
`./static/cards` Данный путь константен. Мб в переменную?

2022-06-03 07:55 UTC, mrerberg commented on src/globals.js
> +export const app = document.querySelector(".app");
Лучше в логике не завязывать на классы в логике, лучше id/дата атрибуты. Они более уникальные и стабильны в плане изменений

2022-06-03 07:55 UTC, mrerberg commented on src/screens/game.js
> +                // todo: очистить openCard
Много туду. Когда их будешь закрывать?

2022-06-03 09:31 UTC, Anastasiia-Kochetkova commented on src/screens/game.js
> +                // todo: очистить openCard
А, в этом дз нужно было сразу для всех сделать? Я не правильно поняла задание значит) Ок, сейчас доделаю.

2022-06-03 09:35 UTC, Anastasiia-Kochetkova commented on src/globals.js
> +export const app = document.querySelector(".app");
Хм, до этого нам говорили избегать id, делать на классах. Спасибо, приму к сведению.

2022-06-03 13:53 UTC, Anastasiia-Kochetkova commented on src/screens/game.js
> +                // todo: очистить openCard
Доработала логику для всех карт. Прошу проверить
https://github.com/Anastasiia-Kochetkova/card-game-skypro/pull/4/commits/2bb86a09b966f228150cab0b1d40c0546f009c7d

2022-06-03 14:37 UTC, Anastasiia-Kochetkova commented on src/card-collection.js
> +        image: "./static/cards/11.jpg",
Хорошо подмечено, сделала! 
https://github.com/Anastasiia-Kochetkova/card-game-skypro/pull/4/commits/bffcda78c280808fff6562b749c52b4924b7f67d

2022-06-05 08:58 UTC, mrerberg commented on src/globals.js
> +export const app = document.querySelector(".app");
id для стилизации избегать, но чтобы завязывать логику (js) на верстке, лучше использовать id или дата атрибуты

2022-06-05 09:02 UTC, mrerberg requested changes

2022-06-05 09:02 UTC, mrerberg commented on src/screens/game.js
>          let imageSrc = undefined;
```
let imageSrc;
```

2022-06-05 09:02 UTC, mrerberg commented on src/screens/game.js
> +            // клик по первой карте
Эти комменты лишние, как мне кажется

2022-06-05 09:02 UTC, mrerberg commented on src/screens/game.js
> +        if (window.application.openCard === undefined) {
Проще синтаксис

```
!window.application.openCard
```

2022-06-06 21:09 UTC, Anastasiia-Kochetkova commented on src/screens/game.js
> +        if (window.application.openCard === undefined) {
Поправила всё здесь https://github.com/Anastasiia-Kochetkova/card-game-skypro/pull/4/commits/b17cffa9c186042eb6b2b2d170a74926b7d0870b

2022-06-07 16:09 UTC, merged