Type script
Anastasiia-Kochetkova/card-game-skypro pull request #6
Opened 2022-06-14 20:29 UTC by Anastasiia-Kochetkova

Подключение TypeScript , конвертация основных JS-файлов в TS.

2022-06-15 16:09 UTC, mrerberg requested changes

2022-06-15 16:09 UTC, mrerberg commented on index.d.ts
> +        application: any; // 👈️ turn off type checking
Так а задай тип вместо any

2022-06-15 16:09 UTC, mrerberg commented on index.d.ts
> +        application: any; // 👈️ turn off type checking
Ты же знаешь, какие там должны быть поля и значения

2022-06-15 16:09 UTC, mrerberg commented on src/globals.ts
> +export function createElement(tagName:string, classList:string|string[], container?:any, textContent?:string):any {
Почему так много `any`?

2022-06-15 16:09 UTC, mrerberg commented on src/screens/game.ts
> +    function cardOnClick(event: any) {
`any` - крайняя необходимость. Ее тут нет

2022-06-15 16:09 UTC, mrerberg commented on src/screens/result.ts
> +    function createMainContainer() {
Почему данная функци (и те, что ниже) объявляются внутри createResultScreen? Это ухудшает ее читаемость

2022-06-30 18:57 UTC, Anastasiia-Kochetkova commented on src/screens/result.ts
> +    function createMainContainer() {
Логика была такой, что  данные функции актуальны только внутри контекста функции отрисовки экрана, поэтому я не стала выносить их в глобальную область видимости. Сейчас попробовала вынести их наружу и, действительно, с параметрами стало более наглядно что где используем и что куда передаём , особенно с TypeScript. 
Вот правки: https://github.com/Anastasiia-Kochetkova/card-game-skypro/pull/6/commits/7a1e811a5a851fce024d21053da21086c6b061dc

2022-07-01 12:30 UTC, Anastasiia-Kochetkova commented on index.d.ts
> +        application: any; // 👈️ turn off type checking
Вот здесь попробовала избавиться от всех "any" и задала тип для window.application: 
 https://github.com/Anastasiia-Kochetkova/card-game-skypro/pull/6/commits/f027538d1b3b949b36d2f7a2e0124bd94235e462

2022-07-03 13:51 UTC, mrerberg requested changes

2022-07-03 13:51 UTC, mrerberg commented on index.d.ts
> +    screens: any,  //здесь не получилось избавиться от any, если пишу тип object, то ошибки при добавлении в него экранов, не смогла их убрать.
А как должен выглядеть объект screens? Какое у него наполнение?

2022-07-03 13:51 UTC, mrerberg commented on src/screens/game.ts
> +    let allCards = [];
Почему let?

https://eslint.org/docs/latest/rules/prefer-const

2022-07-03 13:51 UTC, mrerberg commented on src/screens/game.ts
> +    if (window.application.difficulty === "1") {
Я бы завел объект, в котором ключами выступали бы уровни сложности, а значениями количество пар. 

```ts
const obj = {
  1: {
    cardsPairs: 3
  }
}
```

2022-07-03 13:51 UTC, mrerberg commented on src/screens/game.ts
> +    if (window.application.difficulty === "1") {
Либо сделать отдельные константы для уровней сложности и количество пар к ним

```ts
const LOW_LEVEL = 1;

const LOW_LEVEL_CARDS_PAIRS = 3;
```

2022-07-03 13:51 UTC, mrerberg commented on src/screens/game.ts
> +function fillWithCards(container: HTMLElement): void {
Почему функция `fillWithCards` и карты генерит, и сеттит еще в window количество  пар? Это разный функционал. Желательно, чтобы функция выполняло одно и только одно действие

2022-12-20 21:26 UTC, Anastasiia-Kochetkova commented on src/globals.ts
> +export function createElement(tagName:string, classList:string|string[], container?:any, textContent?:string):any {
Исправлено

2022-12-20 21:27 UTC, Anastasiia-Kochetkova commented on src/screens/game.ts
> +    function cardOnClick(event: any) {
Исправлено

2022-12-20 21:42 UTC, Anastasiia-Kochetkova commented on index.d.ts
> +    screens: any,  //здесь не получилось избавиться от any, если пишу тип object, то ошибки при добавлении в него экранов, не смогла их убрать.
Попробовала уйти от этого any с помощью type Record. Вот здесь все правки https://github.com/Anastasiia-Kochetkova/card-game-skypro/pull/6/commits/84ed922b8c0279760f2d428814857f51e1cefa09

2022-12-20 22:05 UTC, Anastasiia-Kochetkova commented on src/screens/game.ts
> +    let allCards = [];
Исправила https://github.com/Anastasiia-Kochetkova/card-game-skypro/pull/6/commits/aec78f0c21b7493757c8de525e3cd58b9e60bafd

2022-12-20 23:38 UTC, Anastasiia-Kochetkova commented on src/screens/game.ts
> +    if (window.application.difficulty === "1") {
Попробовала переделать через объект. Вот что получилось https://github.com/Anastasiia-Kochetkova/card-game-skypro/pull/6/commits/9516b4642e6a40f980f6c0e8f2f6a56e403a9fd7

2022-12-21 19:33 UTC, Anastasiia-Kochetkova commented on src/screens/game.ts
> +function fillWithCards(container: HTMLElement): void {
Согласна, вот немного причесала функции https://github.com/Anastasiia-Kochetkova/card-game-skypro/pull/6/commits/fcbbd98b3c800b98083efdf5959ee5ee8107bc44

2022-12-26 13:10 UTC, merged